project:
  type: website
  output-dir: docs

website:
  title: "In memory of Evelyne Sernagor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
##      - about.qmd               

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



