project:
  type: website
  output-dir: docs
  pre-render: generate-gallery.ts

website:
  title: "Evelyne Sernagor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: galleries.qmd
        text: Gallery

resources:
  - CNAME

